language: python
sudo: false
python:
    - '2.7'
virtualenv:
  system_site_packages: false
addons:
  apt:
    packages:
        - python-pip
cache:
  directories:
      - "$HOME/.cache"
      - "$HOME/.ccache"
before_install:
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    - pip install --upgrade pip
    - pip install -r requirements.txt
install:
    - python setup.py develop
script:
    - pip install -r dev_requirements.txt
    - flake8 .
    - python -m unittest discover
    - pip install -r doc_requirements.txt
    - sphinx-build -W doc/source doc/build/sphinx
after_success:
    - codecov
