build: false
shallow_clone: true
environment:

  global:
    distutils_use_sdk: 1

  matrix:
    - python: "C:/Python27-x64"
      sdkver: "v7.0"

cache:
  - '%localappdata%\pip\cache -> appveyor-install.cmd'

init:
  - ps: $Env:sdkbin = "C:\Program Files\Microsoft SDKs\Windows\" + $Env:sdkver + "\Bin"
  - ps: $Env:sdkverpath = "C:/Program Files/Microsoft SDKs/Windows/" + $Env:sdkver + "/Setup/WindowsSdkVer.exe"
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:sdkbin + ";" + $Env:path
  - ps: $Env:pip_bootstrap = $Env:temp + "\get-pip.py"
install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', $Env:pip_bootstrap)
  - ps: python $Env:pip_bootstrap
  - "%PYTHON%\\python.exe -m pip install wheel"
  - ps: pip --version
  - cmd /v:on /e:on /c ".\appveyor-install.cmd"
test_script:
  - cmd /v:on /e:on /c ".\appveyor-test.cmd"
